# Generated by Django 4.1.5 on 2023-04-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='city',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='userdata',
            name='state',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
